/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ImagemJar;
import Controle.CRUD;
import Modelo.Usuarios;
import static java.lang.Thread.sleep;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rodrigues
 */
public class BarraProgresso extends javax.swing.JFrame {

    CRUD obc = new CRUD();
    List<Usuarios> usuarios = obc.buscaUtilizador();
    ImagemJar ij = new ImagemJar();

    /**
     * Creates new form BarraProgresso
     */
    public BarraProgresso() {
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(ij.getImageIcon("/Imagens/Hamburger.png").getImage());

        //Barra de Progresso
        new Thread() {
            @Override
            public void run() {
                for (int i = 0; i <= 101; i++) {
                    try {
                        sleep(100);
                        barraProgresso.setValue(i);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(BarraProgresso.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    switch (i) {
                        case 101:
                            if (!usuarios.isEmpty()) {
                                dispose();
                                new Login().setVisible(true);
                            } else {
                                dispose();
                                new MenuPrincipal().setVisible(true);
                            }
                            break;
                        case 15:
                            lbMessagem.setText("Connectando a  Base de dados...");
                            break;
                        case 30:
                            lbMessagem.setText("Base  de Dados connectada.");
                            break;
                        case 45:
                            lbMessagem.setText("Carregando de Modulos...");
                            break;
                        case 60:
                            lbMessagem.setText("Carga de Modulos Terminada.");
                            break;
                        case 75:
                            lbMessagem.setText("Carregando Componentes do Sistema...");
                            break;
                        case 90:
                            lbMessagem.setText("Seja Bem vindo ao Sistema!!!");{
                            try {
                                sleep(10000);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(BarraProgresso.class.getName()).log(Level.SEVERE, null, ex);
                            }
                    }
                            break;
                        default:
                            break;
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSplesh = new javax.swing.JPanel();
        lbMessagem = new javax.swing.JLabel();
        lbImagem = new javax.swing.JLabel();
        barraProgresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSplesh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMessagem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbMessagem.setText("Iniciando o Carregamento do Sistema...");
        panelSplesh.add(lbMessagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 254, 480, 30));

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sanduiche.jpg"))); // NOI18N
        panelSplesh.add(lbImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 280));

        getContentPane().add(panelSplesh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 280));

        barraProgresso.setStringPainted(true);
        getContentPane().add(barraProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 490, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarraProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarraProgresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgresso;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbMessagem;
    private javax.swing.JPanel panelSplesh;
    // End of variables declaration//GEN-END:variables
}
