/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ImagemJar;
import Controle.CRUD;
import Modelo.Itens_Reserva;
import Modelo.Mesas;
import Modelo.Reserva;
import static Visao.MenuPrincipal.panelComponentes;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigues
 */
public class ConsultarReservas extends javax.swing.JDialog {

    CRUD obc = new CRUD();
    private DefaultTableModel modelo;
    ImagemJar ij = new ImagemJar();

    /**
     * Creates new form ConsultarReservas
     */
    public ConsultarReservas() {
        super(new JFrame(), true);
        initComponents();
        setLocationRelativeTo(null);
        tabela();
        ButtonGroup b = new ButtonGroup();
        b.add(btDestivar);   b.add(btCancel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTodosComponentes = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelTabelas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaReservas = new javax.swing.JTable();
        btMesa = new javax.swing.JButton();
        panelPesquisar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtPesquisar = new javax.swing.JTextField();
        btDestivar = new javax.swing.JRadioButton();
        btCancel = new javax.swing.JRadioButton();
        panelDetalhes = new javax.swing.JPanel();
        jtDetalhesReserva = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTodosComponentes.setBackground(new java.awt.Color(255, 255, 255));
        panelTodosComponentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTodosComponentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(51, 141, 252));
        panelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lbTitulo.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setText("Consulta de Reservas");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(lbTitulo)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTodosComponentes.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 70));

        panelTabelas.setBackground(new java.awt.Color(255, 255, 255));
        panelTabelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Mesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N
        panelTabelas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaReservas = new javax.swing.JTable(){
            public boolean isCellEditable(int a,int b){
                return false;
            }
        };
        tabelaReservas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabelaReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelaReservasMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaReservas);

        panelTabelas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 600, 210));

        btMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mesaVazia.png"))); // NOI18N
        btMesa.setToolTipText("Voltar as Mesas");
        btMesa.setBorderPainted(false);
        btMesa.setContentAreaFilled(false);
        btMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMesaActionPerformed(evt);
            }
        });
        panelTabelas.add(btMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 50, 60));

        panelPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        panelPesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPesquisar.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelPesquisar.add(jLabel4);
        jLabel4.setBounds(0, 0, 30, 26);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPesquisar.setForeground(new java.awt.Color(102, 102, 102));
        jtPesquisar.setText("Pesquisar uma reserva por ID ,Codigo da Reserva,ou por Estado");
        jtPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisarActionPerformed(evt);
            }
        });
        jtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusLost(evt);
            }
        });
        jtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyReleased(evt);
            }
        });
        panelPesquisar.add(jtPesquisar);
        jtPesquisar.setBounds(30, 6, 500, 20);

        panelTabelas.add(panelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 540, 30));

        btDestivar.setBackground(new java.awt.Color(255, 255, 255));
        btDestivar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDestivar.setText("Desativar Reserva");
        btDestivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDestivarMousePressed(evt);
            }
        });
        btDestivar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btDestivarItemStateChanged(evt);
            }
        });
        btDestivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDestivarActionPerformed(evt);
            }
        });
        panelTabelas.add(btDestivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btCancel.setBackground(new java.awt.Color(255, 255, 255));
        btCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCancel.setText("Cancelar Reserva");
        btCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCancelMousePressed(evt);
            }
        });
        btCancel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btCancelItemStateChanged(evt);
            }
        });
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        panelTabelas.add(btCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        panelTodosComponentes.add(panelTabelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 620, 310));

        panelDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        panelDetalhes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalhes da Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N
        panelDetalhes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtDetalhesReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelDetalhes.add(jtDetalhesReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 30));

        panelTodosComponentes.add(panelDetalhes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 620, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTodosComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTodosComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMesaActionPerformed
        dispose();
        panelComponentes.removeAll();
        panelComponentes.add(new PainelMesa());
        panelComponentes.validate();
    }//GEN-LAST:event_btMesaActionPerformed

    private void jtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisarActionPerformed

    private void jtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusGained
        jtPesquisar.setText("");
        jtPesquisar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtPesquisarFocusGained

    private void jtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusLost

        jtPesquisar.setForeground(new Color(102, 102, 102));
        jtPesquisar.setText("Pesquisar uma mesa por codigo ou por nome");
    }//GEN-LAST:event_jtPesquisarFocusLost

    private void jtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyReleased
        pesquisarReservas(jtPesquisar.getText(), obc.buscaReservas(), new ArrayList<Reserva>());
    }//GEN-LAST:event_jtPesquisarKeyReleased

    private void tabelaReservasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaReservasMousePressed
        if (jtDetalhesReserva.getSelectedItem() == null) {
            imprimeDetalhes(tabelaReservas.getSelectedRow(), obc.buscaItensReservas());
        } else {
            jtDetalhesReserva.removeAllItems();
            imprimeDetalhes(tabelaReservas.getSelectedRow(), obc.buscaItensReservas());
        }
    }//GEN-LAST:event_tabelaReservasMousePressed

    private void btDestivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDestivarActionPerformed
        int idx = tabelaReservas.getSelectedRow();
        if (idx != -1) {
            desativarReserva(obc.buscaReservas(), tabelaReservas.getSelectedRow());
            atualizarMesas(obc.buscaMesas());
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione a Mesa que Desaja Desativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btDestivarActionPerformed

    private void btDestivarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btDestivarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btDestivarItemStateChanged

    private void btDestivarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDestivarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDestivarMousePressed

    private void btCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCancelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelMousePressed

    private void btCancelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btCancelItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btCancelItemStateChanged

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        if (Objects.equals(jtDetalhesReserva.getSelectedItem(), null)) {
            JOptionPane.showMessageDialog(null, "Selecione a Reserva que deseja Cancelar!", "Messagem", 2);
        } else {
            cancelamentoReserva(obc.buscaReservas(), tabelaReservas.getSelectedRow());
            atualizarMesas(obc.buscaMesas());
        }
    }//GEN-LAST:event_btCancelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConsultarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConsultarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConsultarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConsultarReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConsultarReservas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btCancel;
    private javax.swing.JRadioButton btDestivar;
    private javax.swing.JButton btMesa;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jtDetalhesReserva;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelDetalhes;
    private javax.swing.JPanel panelPesquisar;
    private javax.swing.JPanel panelTabelas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelTodosComponentes;
    private javax.swing.JTable tabelaReservas;
    // End of variables declaration//GEN-END:variables

    private void tabela() {
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nº da Reserva");
        modelo.addColumn("Cliente");
        modelo.addColumn("Data");
        modelo.addColumn("Nº de Pessoas");
        modelo.addColumn("Estado");
        tabelaReservas.setModel(modelo);
        tabelaReservas.getColumnModel().getColumn(0).setPreferredWidth(20);
        tabelaReservas.getColumnModel().getColumn(3).setPreferredWidth(100);

        listarNaTabela(obc.buscaReservas());
    }

    public void listarNaTabela(List<Reserva> reserva) {
        controlaLinhas();
        if (!reserva.isEmpty()) {
            for (int i = 0; i < reserva.size(); i++) {
                Reserva res = reserva.get(i);
                modelo.addRow(new Object[]{res.getIdReserva(), res.getCodigoReserva(), res.getCliente().getNomeCli(), res.getData(), res.getNumPessoas(), res.getEstado()});
            }
        }
    }

    private void controlaLinhas() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void listarPratosPesquisados(ArrayList<Reserva> r) {
        controlaLinhas();
        for (int i = 0; i < r.size(); i++) {
            Reserva res = r.get(i);
            modelo.addRow(new Object[]{res.getIdReserva(), res.getCodigoReserva(), res.getCliente().getNomeCli(), res.getData(), res.getNumPessoas(), res.getEstado()});
        }
    }

    private void pesquisarReservas(String n, List<Reserva> res, ArrayList<Reserva> reserva) {
        for (int i = 0; i < res.size(); i++) {
            Reserva r = res.get(i);
            if (r.getCliente().getNomeCli().toLowerCase().startsWith(n) || String.valueOf(r.getIdReserva()).startsWith(n) || String.valueOf(r.getEstado()).toLowerCase().startsWith(n)) {
                reserva.add(r);
            }
        }
        listarPratosPesquisados(reserva);
    }

    private void imprimeDetalhes(int linha, List<Itens_Reserva> itens) {
        int id = (int) tabelaReservas.getValueAt(linha, 0);
        for (int i = 0; i < itens.size(); i++) {
            Itens_Reserva get = itens.get(i);
            if (get.getReserva().getIdReserva() == id) {
                jtDetalhesReserva.addItem(get.getMesa().getNomeMesa());
            }
        }
    }

    private void cancelamentoReserva(List<Reserva> reservas, int linha) {
        for (int i = 0; i < reservas.size(); i++) {
            Reserva res = reservas.get(i);
            if (Objects.equals(res.getIdReserva(), (Integer) tabelaReservas.getValueAt(linha, 0))) {
                int confirmacao = JOptionPane.showConfirmDialog(null, "Desejas Realmente cancelar a reserva", "Messagem", JOptionPane.OK_CANCEL_OPTION);
                if (confirmacao == JOptionPane.OK_OPTION) {
                    res.setEstado("Cancelado");
                    obc.actualizar(res);
                    JOptionPane.showMessageDialog(null, "Cancelado com Sucesso", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/Delete.png").getImage()));
                    listarNaTabela(obc.buscaReservas());
                    break;
                }
            }

        }
    }

    private void atualizarMesas(List<Mesas> mesas) {
        for (int i = 1; i < mesas.size() + 1; i++) {
            Mesas mes = mesas.get(i - 1);
            for (int j = 0; j < jtDetalhesReserva.getItemCount(); j++) {
                if (mes.getNomeMesa().equalsIgnoreCase(jtDetalhesReserva.getItemAt(j))) {
                    mes.setEstado("Livre");
                    obc.actualizar(mes);
                }
            }

        }
    }

    private void desativarReserva(List<Reserva> reservas, int linha) {
        for (int i = 0; i < reservas.size(); i++) {
            Reserva res = reservas.get(i);
            if (Objects.equals(res.getIdReserva(), (Integer) tabelaReservas.getValueAt(linha, 0))) {
                res.setEstado("Desativado");
                obc.actualizar(res);
                JOptionPane.showMessageDialog(null, "Desativado com Sucesso", "Messagem", 1);
                listarNaTabela(obc.buscaReservas());
                break;
            }
        }
    }
}
