/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ImagemJar;
import Controle.CRUD;
import Modelo.Clientes;
import Modelo.Itens_Reserva;
import Modelo.Mesas;
import Modelo.Reserva;
import static Visao.MenuPrincipal.panelComponentes;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigues
 */
public class FormularioReservas extends javax.swing.JDialog {

    /**
     * Creates new form Reservas
     */

    ImagemJar jar = new ImagemJar();

    public FormularioReservas() {
        super(new JFrame(), true);
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        jtPessoas.setValue(1);
        mesas(obc.buscaMesas());
        codigoPedido();
        jtData.setDateFormatString("dd/MM/yyyy");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComponente = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDadosReserva = new javax.swing.JPanel();
        jtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbNumReserva = new javax.swing.JLabel();
        jtPessoas = new javax.swing.JSpinner();
        lbCliente = new javax.swing.JLabel();
        btCliente = new javax.swing.JButton();
        lbMesas = new javax.swing.JLabel();
        jtNumReserva = new javax.swing.JTextField();
        jtMesasEscolhidas = new javax.swing.JComboBox<>();
        lbNumPessoas = new javax.swing.JLabel();
        lbMesas1 = new javax.swing.JLabel();
        jtMesas = new javax.swing.JComboBox<>();
        jtData = new com.toedter.calendar.JDateChooser();
        panelCrud = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btGravar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelComponente.setBackground(new java.awt.Color(255, 255, 255));
        panelComponente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelComponente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitulo.setBackground(new java.awt.Color(51, 141, 252));
        panelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario de Reservas");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(113, 113, 113))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComponente.add(panelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        panelDadosReserva.setBackground(new java.awt.Color(255, 255, 255));
        panelDadosReserva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Reserva", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N
        panelDadosReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtCliente.setFocusable(false);
        panelDadosReserva.add(jtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 280, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data:");
        panelDadosReserva.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lbNumReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNumReserva.setText("Nº da Reserva:");
        panelDadosReserva.add(lbNumReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtPessoas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelDadosReserva.add(jtPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 310, 30));

        lbCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCliente.setText("Cliente:");
        panelDadosReserva.add(lbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.png"))); // NOI18N
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        panelDadosReserva.add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 30, 30));

        lbMesas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMesas.setText("Mesas Escolhidas:");
        panelDadosReserva.add(lbMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jtNumReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNumReserva.setFocusable(false);
        panelDadosReserva.add(jtNumReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 310, 30));

        jtMesasEscolhidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panelDadosReserva.add(jtMesasEscolhidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 310, 30));

        lbNumPessoas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNumPessoas.setText("Nº de Pessoas:");
        panelDadosReserva.add(lbNumPessoas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lbMesas1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMesas1.setText("Mesas:");
        panelDadosReserva.add(lbMesas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jtMesas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione as Mesas" }));
        jtMesas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtMesasItemStateChanged(evt);
            }
        });
        panelDadosReserva.add(jtMesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 310, 30));
        panelDadosReserva.add(jtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 310, 30));

        panelComponente.add(panelDadosReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 270));

        panelCrud.setBackground(new java.awt.Color(255, 255, 255));
        panelCrud.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelCrud.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });
        panelCrud.add(btGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 90, 30));

        btSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSair.setText("Mesas");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        panelCrud.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 30));

        btGravar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btGravar1.setText("Remover");
        btGravar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravar1ActionPerformed(evt);
            }
        });
        panelCrud.add(btGravar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 90, 30));

        panelComponente.add(panelCrud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 480, 50));

        getContentPane().add(panelComponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
        panelComponentes.removeAll();
        panelComponentes.add(new PainelMesa());
        panelComponentes.validate();
    }//GEN-LAST:event_btSairActionPerformed

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        reserva = "reserva";
        new ListaClientes().setVisible(true);
    }//GEN-LAST:event_btClienteActionPerformed

    private void jtMesasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtMesasItemStateChanged
        selecionarMesas(jtMesas.getSelectedItem().toString());
    }//GEN-LAST:event_jtMesasItemStateChanged

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        gravar();
        codigoPedido();
    }//GEN-LAST:event_btGravarActionPerformed

    private void btGravar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravar1ActionPerformed
        if (jtMesasEscolhidas.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "A Componentes de Mesas Escolhidas nao Pode estar vazia", "Messagem", 2);

        } else {
            jtMesasEscolhidas.removeItem(jtMesasEscolhidas.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Removido com Sucesso!!!", "Messagem", 1, new ImageIcon(jar.getImageIcon("/Imagens/Delete.png").getImage()));
        }
    }//GEN-LAST:event_btGravar1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormularioReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormularioReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormularioReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormularioReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormularioReservas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btGravar1;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JTextField jtCliente;
    private com.toedter.calendar.JDateChooser jtData;
    private javax.swing.JComboBox<String> jtMesas;
    private javax.swing.JComboBox<String> jtMesasEscolhidas;
    private javax.swing.JTextField jtNumReserva;
    private javax.swing.JSpinner jtPessoas;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbMesas;
    private javax.swing.JLabel lbMesas1;
    private javax.swing.JLabel lbNumPessoas;
    private javax.swing.JLabel lbNumReserva;
    private javax.swing.JPanel panelComponente;
    private javax.swing.JPanel panelCrud;
    private javax.swing.JPanel panelDadosReserva;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
    public static String reserva = null;
    CRUD obc = new CRUD();
    private String codigo = "00000";

    private void codigoPedido() {
        String cod = "";
        int codigo = 0;
        for (int i = 1; i <= obc.buscaReservas().size() + 1; i++) {
            codigo = i;
            String tamanho = "" + codigo;
            cod = this.codigo.substring(0, this.codigo.length() - tamanho.length());
        }
        jtNumReserva.setText(String.valueOf(cod + codigo));
    }

    private void mesas(List<Mesas> mesas) {
        for (int i = 1; i < mesas.size() + 1; i++) {
            Mesas mesa = mesas.get(i - 1);
            jtMesas.addItem(mesa.getNomeMesa());
        }
    }

    private void selecionarMesas(String mesa) {
        if (mesa.equalsIgnoreCase("Selecione as Mesas")) {
        } else {
            int idx = jtMesasEscolhidas.getItemCount();
            if (idx == 0) {
                jtMesasEscolhidas.addItem(mesa);
            } else {
                for (int i = 0; i < idx; i++) {
                    if (jtMesasEscolhidas.getItemAt(idx - 1).equals(mesa)) {
                        break;
                    } else {
                        jtMesasEscolhidas.addItem(mesa);
                        break;
                    }
                }
            }

        }
    }

    private void listaItens(Reserva idReserva, List<Mesas> mesas) {
        for (int k = 0; k < jtMesasEscolhidas.getItemCount(); k++) {

            for (int i = 1; i < mesas.size() + 1; i++) {
                Mesas idMesa = mesas.get(i - 1);
                if (jtMesasEscolhidas.getItemAt(k).equalsIgnoreCase(idMesa.getNomeMesa())) {
                    idMesa.setEstado("Reservado");
                    obc.actualizar(idMesa);
                    Itens_Reserva ir = new Itens_Reserva(idReserva, idMesa);
                    obc.salvar(ir);
                }
            }
        }

    }

    private void gravar() {
        Reserva res = new Reserva(jtNumReserva.getText(), cliente(obc.buscaClientess()), jtData.getDate(), (int) jtPessoas.getValue(), "Ativa");
        listaItens(res, obc.buscaMesas());
        JOptionPane.showMessageDialog(null, "Salvado com Sucesso", "Messagem", 1, new ImageIcon(jar.getImageIcon("/Imagens/salvar.png").getImage()));
    }

    private Clientes cliente(List<Clientes> buscaClientes) {
        Clientes cliente = null;
        for (int i = 0; i < buscaClientes.size(); i++) {
            Clientes c = buscaClientes.get(i);
            if (c.getNomeCli().equalsIgnoreCase(jtCliente.getText())) {
                cliente = c;
                break;
            }
        }
        return cliente;
    }

}
