/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CRUD;
import Modelo.Mesas;
import static Visao.MenuPrincipal.panelComponentes;
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigues
 */
public class ListaMesas extends javax.swing.JDialog {

    CRUD obc = new CRUD();
    private DefaultTableModel modelo = new DefaultTableModel(new String[]{"ID","Nome","Lotação","Estado"},0);
    private Image url;

    /**
     * Creates new form ConsultasMesa
     */
    public ListaMesas() {
        super(new JFrame(), true);
        initComponents();
        setLocationRelativeTo(null);
        tabela();
        ButtonGroup b = new ButtonGroup();
        b.add(btAtivar);
        b.add(btDestivar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        butaoMesa = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtPesquisar = new javax.swing.JTextField();
        btAtivar = new javax.swing.JRadioButton();
        btDestivar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(url);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 141, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta de Mesas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Mesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 20), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela = new javax.swing.JTable(){
            public boolean isCellEditable(int a,int b){
                return false;
            }
        };
        tabela.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 500, 230));

        butaoMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        butaoMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mesaVazia.png"))); // NOI18N
        butaoMesa.setToolTipText("Voltar As Mesas");
        butaoMesa.setBorderPainted(false);
        butaoMesa.setContentAreaFilled(false);
        butaoMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoMesaActionPerformed(evt);
            }
        });
        jPanel5.add(butaoMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, 60));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel9.add(jLabel4);
        jLabel4.setBounds(0, 0, 30, 26);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPesquisar.setForeground(new java.awt.Color(102, 102, 102));
        jtPesquisar.setText("Pesquisar uma mesa por codigo ou por nome");
        jtPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisarActionPerformed(evt);
            }
        });
        jtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusLost(evt);
            }
        });
        jtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyReleased(evt);
            }
        });
        jPanel9.add(jtPesquisar);
        jtPesquisar.setBounds(30, 6, 410, 20);

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 450, 30));

        btAtivar.setBackground(new java.awt.Color(255, 255, 255));
        btAtivar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtivar.setText("Ativar Mesa");
        btAtivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btAtivarMousePressed(evt);
            }
        });
        btAtivar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btAtivarItemStateChanged(evt);
            }
        });
        btAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtivarActionPerformed(evt);
            }
        });
        jPanel5.add(btAtivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btDestivar.setBackground(new java.awt.Color(255, 255, 255));
        btDestivar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDestivar.setText("Desativar Mesa");
        btDestivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDestivarMousePressed(evt);
            }
        });
        btDestivar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btDestivarItemStateChanged(evt);
            }
        });
        btDestivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDestivarActionPerformed(evt);
            }
        });
        jPanel5.add(btDestivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 520, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoMesaActionPerformed
        dispose();
        panelComponentes.removeAll();
        panelComponentes.add(new PainelMesa());
        panelComponentes.validate();
    }//GEN-LAST:event_butaoMesaActionPerformed

    private void jtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisarActionPerformed

    private void jtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusGained
        jtPesquisar.setText("");
        jtPesquisar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtPesquisarFocusGained

    private void jtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusLost

        jtPesquisar.setForeground(new Color(102, 102, 102));
        jtPesquisar.setText("Pesquisar uma mesa por codigo ou por nome");
    }//GEN-LAST:event_jtPesquisarFocusLost

    private void jtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyReleased
        pesquisarMesa(jtPesquisar.getText(), obc.buscaMesas(), new ArrayList<Mesas>());
    }//GEN-LAST:event_jtPesquisarKeyReleased

    private void btAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtivarActionPerformed
        int idx = tabela.getSelectedRow();
        if (idx != -1) {
            ativarMesa(obc.buscaMesas(), (int) tabela.getValueAt(tabela.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione a Mesa que Desaja Ativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btAtivarActionPerformed

    private void btAtivarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAtivarMousePressed
    }//GEN-LAST:event_btAtivarMousePressed

    private void btAtivarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btAtivarItemStateChanged
        // desativarMesa(obc.buscaMesas());
    }//GEN-LAST:event_btAtivarItemStateChanged

    private void btDestivarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDestivarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDestivarMousePressed

    private void btDestivarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btDestivarItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btDestivarItemStateChanged

    private void btDestivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDestivarActionPerformed
        int idx = tabela.getSelectedRow();
        if (idx != -1) {
            desativarMesa(obc.buscaMesas(), (int) tabela.getValueAt(tabela.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione a Mesa que Desaja Desativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btDestivarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btAtivar;
    private javax.swing.JRadioButton btDestivar;
    private javax.swing.JButton butaoMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
public void removerNaTabela(List<Mesas> mesa) {
        int codigo = tabela.getSelectedRow();
        if (codigo == -1) {
            JOptionPane.showMessageDialog(null, "Selecione o Usuario que deseja remover!!!", "messagem", 0);
        } else {
            String nome = (String) tabela.getValueAt(codigo, 1);
            for (int i = 0; i < mesa.size(); i++) {
                String nome2 = (String) tabela.getValueAt(i, 1);
                if (nome.equals(nome2)) {

                    int j = JOptionPane.showConfirmDialog(null, "Deseja realmente Remover Esta Mesa", "Messagem", 2);
                    if (j == JOptionPane.OK_OPTION) {
                        obc.excluir(mesa.get(i));
                        JOptionPane.showMessageDialog(null, "Removido com Sucesso!!!", "Messagem", 1, new ImageIcon(getClass().getResource("imagens/Delete.png")));
                    }
                    listarNaTabela(obc.buscaMesas());
                    break;
                }
            }
        }

    }//remover

    /**
     * Este metodo e responsavel por listar os dados na tabela do sistema em
     * tempo real
     *
     * @param mesa
     */
    public void listarNaTabela(List<Mesas> mesa) {
        controlaLinhas();
        if (!mesa.isEmpty()) {
            for (int i = 0; i < mesa.size(); i++) {
                Mesas m = mesa.get(i);
                modelo.addRow(new Object[]{m.getCodMesa(), m.getNomeMesa(),m.getTamanho(), m.getEstado()});
            }
        }
    }
///=========================================

    /**
     * Este metodo e responsavel por definir as colunas da tabela
     */
    private void tabela() {

        tabela.setModel(modelo);
        listarNaTabela(obc.buscaMesas());
    }

    private void pesquisarMesa(String n, List<Mesas> mesa, ArrayList<Mesas> p) {
        for (int i = 0; i < mesa.size(); i++) {
            Mesas mes = mesa.get(i);
            if (mes.getNomeMesa().toLowerCase().startsWith(n) || String.valueOf(mes.getCodMesa()).startsWith(n) || String.valueOf(mes.getEstado()).toLowerCase().startsWith(n)) {
                p.add(mes);
            }
        }
        listarPratosPesquisados(p);
    }

    private void listarPratosPesquisados(ArrayList<Mesas> m) {
        controlaLinhas();
        for (int i = 0; i < m.size(); i++) {
            Mesas mesa = m.get(i);
            modelo.addRow(new Object[]{mesa.getCodMesa(), mesa.getNomeMesa(), mesa.getLugares(), mesa.getTamanho(), mesa.getEstado()});
        }
    }

    private void controlaLinhas() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void desativarMesa(List<Mesas> mesa, int id) {

        for (int i = 1; i < mesa.size() + 1; i++) {
            Mesas buscaMesa = mesa.get(i - 1);
            if (buscaMesa.getEstado().equalsIgnoreCase("cheio") || buscaMesa.getEstado().equalsIgnoreCase("ocupado")) {
                JOptionPane.showMessageDialog(null, "Esta Mesa nao pode ser desativada,pois contem pedidos.", "Messagem", 2);
                break;
            } else if (buscaMesa.getEstado().equalsIgnoreCase("Desativada") && buscaMesa.getCodMesa() == id) {
                JOptionPane.showMessageDialog(null, "Esta Mesa ja esta desativada!", "Messagem", 2);
                break;
            } else if (buscaMesa.getCodMesa() == id) {
                buscaMesa.setEstado("Desativada");
                obc.actualizar(buscaMesa);
                JOptionPane.showMessageDialog(null, "Mesa desativada com Sucesso", "Messagem", 1);
                listarNaTabela(obc.buscaMesas());
                break;
            }
        }
    }

    private void ativarMesa(List<Mesas> buscaMesas, int id) {
        for (int i = 1; i < buscaMesas.size() + 1; i++) {
            Mesas buscaMesa = buscaMesas.get(i - 1);
            if ((buscaMesa.getEstado().equalsIgnoreCase("cheio") || buscaMesa.getEstado().equalsIgnoreCase("ocupado") || buscaMesa.getEstado().equalsIgnoreCase("Livre")) && buscaMesa.getCodMesa() == id) {
                JOptionPane.showMessageDialog(null, "A Mesa ja esta Activa!", "Messagem", 2);
                break;
            } else if (buscaMesa.getCodMesa() == id) {
                buscaMesa.setEstado("Livre");
                obc.actualizar(buscaMesa);
                JOptionPane.showMessageDialog(null, "Mesa ativada com Sucesso!", "Messagem", 1);
                listarNaTabela(obc.buscaMesas());
                break;
            }
        }

    }

}
