/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CRUD;
import Modelo.Clientes;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigues
 */
public final class ListaClientes extends javax.swing.JDialog {

    DefaultTableModel modelo = new DefaultTableModel(new String[]{"ID", "Nome", "Apelido"}, 0);
    CRUD obc = new CRUD();

    /**
     * Creates new form ListaClientes
     */
    public ListaClientes() {
        super(new JFrame(), true);
        initComponents();
        tabelaClientes.setModel(modelo);
        setLocationRelativeTo(null);
        listarNaTabela(obc.buscaClientess(), null);
        tabelaClientes.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                int codigo = tabelaClientes.getSelectedRow();
                jtNome.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 1)));
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtNome = new javax.swing.JTextField();
        btCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtPesquisar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 141, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 20), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNome.setFocusable(false);
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });
        jPanel3.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 27, 650, 30));

        btCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/nova.png"))); // NOI18N
        btCliente.setToolTipText("Pequisar um Cliente");
        btCliente.setBorderPainted(false);
        btCliente.setContentAreaFilled(false);
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        jPanel3.add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 29, 39, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 20), new java.awt.Color(0, 153, 255))); // NOI18N
        jPanel4.setLayout(null);

        tabelaClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int a,int b){
                return false;
            }
        };
        tabelaClientes.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaClientes);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 660, 230);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel9.add(jLabel4);
        jLabel4.setBounds(0, 0, 30, 26);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPesquisar.setForeground(new java.awt.Color(102, 102, 102));
        jtPesquisar.setText("Pesquisar cliente por nome ,codigo ou apelido");
        jtPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisarActionPerformed(evt);
            }
        });
        jtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusLost(evt);
            }
        });
        jtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyReleased(evt);
            }
        });
        jPanel9.add(jtPesquisar);
        jtPesquisar.setBounds(30, 6, 370, 20);

        jPanel4.add(jPanel9);
        jPanel9.setBounds(160, 30, 410, 30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
        adicionarNomeTxtField();
    }//GEN-LAST:event_btClienteActionPerformed

    private void jtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisarActionPerformed

    private void jtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusGained
        jtPesquisar.setText("");
        jtPesquisar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtPesquisarFocusGained

    private void jtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusLost
        jtPesquisar.setForeground(new Color(102, 102, 102));
        jtPesquisar.setText("Pesquisar cliente por nome ,codigo ou apelido");
    }//GEN-LAST:event_jtPesquisarFocusLost

    private void jtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyReleased
        pesquisarClientes(jtPesquisar.getText(), obc.buscaClientess(), new ArrayList(), null);
    }//GEN-LAST:event_jtPesquisarKeyReleased

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            adicionarNomeTxtField();
        }
    }//GEN-LAST:event_jtNomeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables
    public void listarNaTabela(List<Clientes> ut, String[] linha) {
        controlasLinhasDaTabela();
        if (!ut.isEmpty()) {
            for (int i = 0; i < ut.size(); i++) {
                Clientes cli = ut.get(i);
                 if (!cli.getNomeCli().equalsIgnoreCase("cliente geral")&&!cli.getEstado().equalsIgnoreCase("Desativado")) { 
                    modelo.addRow(new Object[]{cli.getCodCliente(), cli.getNomeCli(), cli.getApelidoCli()});
                }
            }

        }

    }

    private void pesquisarClientes(String n, List<Clientes> cli, ArrayList<Clientes> p, String[] linha) {
        controlasLinhasDaTabela();
        for (int i = 0; i < cli.size(); i++) {
            Clientes cliente = cli.get(i);
            if (cliente.getNomeCli().toLowerCase().startsWith(n) || String.valueOf(cliente.getCodCliente()).startsWith(n) || cliente.getApelidoCli().toLowerCase().startsWith(n)) {
                p.add(cliente);
            }
        }
        listarClientesPesquisados(p, linha);
    }

    private void listarClientesPesquisados(ArrayList<Clientes> p, String[] linha) {
        for (int i = 0; i < p.size(); i++) {
            Clientes produto = p.get(i);
            modelo.addRow(linha);
            modelo.setValueAt(produto.getCodCliente(), i, 0);
            modelo.setValueAt(produto.getNomeCli(), i, 1);
            modelo.setValueAt(produto.getApelidoCli(), i, 2);
        }
    }

    private void controlasLinhasDaTabela() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void adicionarNomeTxtField() {
        if (FormularioReservas.reserva != null) {
            FormularioReservas.jtCliente.setText(jtNome.getText());
            dispose();
        } else if(!jtNome.getText().equals("")){ 
            PainelVenda.jtCliente.setText(jtNome.getText());
            PainelVenda.jtCliente.setForeground(Color.BLACK);
            dispose();
        }else{
            dispose();
        }
    }

}
