/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ImagemJar;
import Controle.CRUD;
import Modelo.Usuarios;
import static Visao.MenuPrincipal.btClientes;
import static Visao.MenuPrincipal.btMesas;
import static Visao.MenuPrincipal.btProdutos;
import static Visao.MenuPrincipal.btUsuario;
import static Visao.MenuPrincipal.btVendas;
import static Visao.MenuPrincipal.lbCargo;
import static Visao.MenuPrincipal.lbUsuario;
import static Visao.MenuPrincipal.menuConsulta;
import java.awt.event.KeyEvent;
import java.net.MalformedURLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static Visao.MenuPrincipal.itemVendedor;

/**
 *
 * @author Rodrigues
 */
public class Login extends javax.swing.JFrame {

    CRUD obc = new CRUD();

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        ImagemJar ij = new ImagemJar();
        this.setIconImage(ij.getImageIcon("/Imagens/Hamburger.png").getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        painelComponente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JPasswordField();
        btSair = new javax.swing.JButton();
        btAcessar = new javax.swing.JButton();
        jtNome = new javax.swing.JTextField();
        jtErro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/garsom.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 70, 170, 210);

        painelComponente.setBackground(new java.awt.Color(255, 255, 255));
        painelComponente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autenticação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 20), new java.awt.Color(0, 153, 255))); // NOI18N
        painelComponente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Utilizador:");
        painelComponente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Senha:");
        painelComponente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        jtSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSenhaActionPerformed(evt);
            }
        });
        jtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtSenhaFocusGained(evt);
            }
        });
        jtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtSenhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtSenhaKeyTyped(evt);
            }
        });
        painelComponente.add(jtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 30));

        btSair.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Shut.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        painelComponente.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, 40));

        btAcessar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ok-24.png"))); // NOI18N
        btAcessar.setText("Acessar");
        btAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcessarActionPerformed(evt);
            }
        });
        btAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btAcessarKeyPressed(evt);
            }
        });
        painelComponente.add(btAcessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 40));

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        jtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtNomeFocusGained(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
        });
        painelComponente.add(jtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, 30));

        jtErro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtErro.setForeground(new java.awt.Color(255, 0, 0));
        painelComponente.add(jtErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, 20));

        jPanel1.add(painelComponente);
        painelComponente.setBounds(10, 70, 300, 210);

        jPanel3.setBackground(new java.awt.Color(51, 141, 252));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Restaurante");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 490, 64);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtSenhaActionPerformed

    private void jtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtSenhaFocusGained
        jtErro.setText("");
    }//GEN-LAST:event_jtSenhaFocusGained

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcessarActionPerformed
        try {
            autenticcao(jtNome.getText(), jtSenha.getText(), obc.buscaUtilizador());
        } catch (MalformedURLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAcessarActionPerformed

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtNomeFocusGained
        jtErro.setText("");
    }//GEN-LAST:event_jtNomeFocusGained

    private void btAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAcessarKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             try {
                 autenticcao(jtNome.getText(), jtSenha.getText(), obc.buscaUtilizador());
             } catch (MalformedURLException ex) {
                 Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_btAcessarKeyPressed

    private void jtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btAcessar.grabFocus();
        }
    }//GEN-LAST:event_jtSenhaKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtSenha.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtSenhaKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            jtNome.grabFocus();
        }
    }//GEN-LAST:event_jtSenhaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcessar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jtErro;
    private javax.swing.JTextField jtNome;
    private javax.swing.JPasswordField jtSenha;
    private javax.swing.JPanel painelComponente;
    // End of variables declaration//GEN-END:variables

    private void autenticcao(String nome, String senha, List<Usuarios> usuarios) throws MalformedURLException {
        boolean achou = false;
        Usuarios usuario = null;

        for (int i = 0; i < usuarios.size(); i++) {
            Usuarios usu = usuarios.get(i);
            if ((nome.equals(usu.getUtilizador()) || nome.equals(usu.getFunc().getCargo().getNomeCargo())) && senha.equals(usu.getSenha())) {
                achou = true;
                usuario = usu;
                break;
            }
        }
        dadodDeUsuario(achou, usuario);
    }

    private void dadodDeUsuario(boolean achou, Usuarios usu) {
        if (achou) {
            if (!usu.getFunc().getEstado().equals("Inativo")) {
                dispose();
                new MenuPrincipal().setVisible(true);
                lbUsuario.setText("Usuario: " + usu.getUtilizador());
                lbCargo.setText("Cargo: " + usu.getFunc().getCargo().getNomeCargo());
                if (usu.getFunc().getCargo().getNomeCargo().equalsIgnoreCase("Administrador")) {
                    btVendas.setEnabled(false);
                    btMesas.setEnabled(false);
                } else if(usu.getFunc().getCargo().getNomeCargo().equalsIgnoreCase("Caixa")){
                    btUsuario.setEnabled(false);
                    itemVendedor.setVisible(false);
                    menuConsulta.setVisible(false);
                    btClientes.setEnabled(false);
                    btProdutos.setEnabled(false);
                }else{JOptionPane.showMessageDialog(null,"Usuario Invalido ao Sistema!","Messagem",1);System.exit(0);} 
            } else {
                JOptionPane.showMessageDialog(null, "ups! Vc encontra-se temporariamente Inativo, contacte o administrador do sistema", "Messagem", 1);
            }
        }else {
              jtErro.setText("Usuario ou Password Invalidos");
        }
    }
        
}
