/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ImagemJar;
import Controle.ArquivoMesa;
import Controle.CRUD;
import Modelo.Mesas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Rodrigues
 */
public class PainelMesa extends javax.swing.JPanel {

    CRUD obc = new CRUD();
    ImagemJar ij = new ImagemJar();
    ArquivoMesa am = new ArquivoMesa();
    private JButton bt = null;
    public static String btk;
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de imagens", "jpg");
    private String caminho = "";

    /**
     * Creates new form PainelMesa
     */
    public PainelMesa() {
        initComponents();
        mostraImagem(am.recuperarCaminho());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelMesas = new javax.swing.JPanel();
        panelDescricao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbDescricao1 = new javax.swing.JLabel();
        lbDescricao2 = new javax.swing.JLabel();
        lbDescricao3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelImage = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        panelTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelControle = new javax.swing.JPanel();
        btMesa = new javax.swing.JButton();
        btExcluirReserva = new javax.swing.JButton();
        btReservar = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane(criaBotaoAutomatico(obc.buscaMesas()));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        PainelMesas.setBackground(new java.awt.Color(255, 255, 255));
        PainelMesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        panelDescricao.setBackground(new java.awt.Color(255, 255, 255));
        panelDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descrição da Mesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ocupada");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Cheia");

        lbDescricao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mesaVazia.png"))); // NOI18N

        lbDescricao2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mesaOcupada.png"))); // NOI18N

        lbDescricao3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mesaCheia.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Livre");

        javax.swing.GroupLayout panelDescricaoLayout = new javax.swing.GroupLayout(panelDescricao);
        panelDescricao.setLayout(panelDescricaoLayout);
        panelDescricaoLayout.setHorizontalGroup(
            panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescricaoLayout.createSequentialGroup()
                .addGroup(panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDescricaoLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDescricaoLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(lbDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDescricaoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDescricaoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lbDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(lbDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelDescricaoLayout.setVerticalGroup(
            panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescricaoLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(lbDescricao2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(3, 3, 3)
                .addGroup(panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescricao3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelImage.setBackground(new java.awt.Color(255, 255, 255));
        panelImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salao1.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImageLayout.createSequentialGroup()
                .addComponent(lbImagem)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 358, Short.MAX_VALUE)
        );

        panelTitulo.setBackground(new java.awt.Color(51, 141, 252));
        panelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Salão de Mesas");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(438, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelControle.setBackground(new java.awt.Color(255, 255, 255));
        panelControle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));

        btMesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addmesa.jpg"))); // NOI18N
        btMesa.setText("Adicionar Mesas");
        btMesa.setToolTipText("");
        btMesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btMesa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMesaActionPerformed(evt);
            }
        });

        btExcluirReserva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btExcluirReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluirR.png"))); // NOI18N
        btExcluirReserva.setText("Excluir Reservas");
        btExcluirReserva.setToolTipText("Essa opcao ainda esta por se integrar");
        btExcluirReserva.setEnabled(false);
        btExcluirReserva.setFocusPainted(false);
        btExcluirReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btExcluirReserva.setPreferredSize(new java.awt.Dimension(127, 57));
        btExcluirReserva.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btExcluirReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btExcluirReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirReservaActionPerformed(evt);
            }
        });

        btReservar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btReservar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reserva.jpg"))); // NOI18N
        btReservar.setText("Reservar Mesas");
        btReservar.setToolTipText("Essa opcao ainda esta por se integrar");
        btReservar.setEnabled(false);
        btReservar.setFocusPainted(false);
        btReservar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btReservar.setPreferredSize(new java.awt.Dimension(127, 57));
        btReservar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btReservar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservarActionPerformed(evt);
            }
        });

        btConsulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consulta.jpg"))); // NOI18N
        btConsulta.setText("Consultar Mesas");
        btConsulta.setToolTipText("");
        btConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btConsulta.setPreferredSize(new java.awt.Dimension(127, 57));
        btConsulta.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControleLayout = new javax.swing.GroupLayout(panelControle);
        panelControle.setLayout(panelControleLayout);
        panelControleLayout.setHorizontalGroup(
            panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControleLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btExcluirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelControleLayout.setVerticalGroup(
            panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelControleLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btExcluirReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollPane.setPreferredSize(new java.awt.Dimension(690, 690));

        javax.swing.GroupLayout PainelMesasLayout = new javax.swing.GroupLayout(PainelMesas);
        PainelMesas.setLayout(PainelMesasLayout);
        PainelMesasLayout.setHorizontalGroup(
            PainelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(PainelMesasLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PainelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(PainelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PainelMesasLayout.setVerticalGroup(
            PainelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelMesasLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(PainelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PainelMesasLayout.createSequentialGroup()
                        .addComponent(panelControle, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelMesasLayout.createSequentialGroup()
                        .addComponent(panelImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        new ListaMesas().setVisible(true);
    }//GEN-LAST:event_btConsultaActionPerformed

    private void btMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMesaActionPerformed
        new FormularioMesa().setVisible(true);
    }//GEN-LAST:event_btMesaActionPerformed

    private void btReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservarActionPerformed
        new FormularioReservas().setVisible(true);
    }//GEN-LAST:event_btReservarActionPerformed

    private void btExcluirReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirReservaActionPerformed
        new ConsultarReservas().setVisible(true);
    }//GEN-LAST:event_btExcluirReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelMesas;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btExcluirReserva;
    private javax.swing.JButton btMesa;
    private javax.swing.JButton btReservar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbDescricao1;
    private javax.swing.JLabel lbDescricao2;
    private javax.swing.JLabel lbDescricao3;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelControle;
    private javax.swing.JPanel panelDescricao;
    private javax.swing.JPanel panelImage;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

    public JPanel criaBotaoAutomatico(List<Mesas> butao) {

        JPanel panelMesas = new JPanel();
        panelMesas.setLayout(new MigLayout());
        panelMesas.setBackground(Color.white);
        panelMesas.setSize(690, 550);

        for (int i = 1; i < butao.size() + 1; i++) {
            Mesas mesa = butao.get(i-1);
                bt = new JButton(String.valueOf(mesa.getNomeMesa()));
                if (mesa.getEstado().equalsIgnoreCase("ocupado")){
                    bt.setIcon(new ImageIcon(ij.getImageIcon("/Imagens/mesaOcupada.png").getImage()));
                } else if (mesa.getEstado().equalsIgnoreCase("cheio")) {
                    bt.setIcon(new ImageIcon(ij.getImageIcon("/Imagens/mesaCheia.png").getImage()));
                } else if (mesa.getEstado().equalsIgnoreCase("Desativada")) {
                    bt.setEnabled(false);
                    bt.setIcon(new ImageIcon(ij.getImageIcon("/Imagens/mesaVazia.png").getImage()));
                } else if (mesa.getEstado().equalsIgnoreCase("Reservado")) {
                    bt.setIcon(new ImageIcon(ij.getImageIcon("/Imagens/mesaReservada.png").getImage()));
                } else {
                    bt.setForeground(Color.black);
                    bt.setIcon(new ImageIcon(getClass().getResource("/Imagens/mesaVazia.png")));
                }
                bt.setLocation(50, 10);
                bt.setFont(new Font("Serif", Font.PLAIN, 16));
                bt.setPreferredSize(new Dimension(105, 100));
                bt.setVerticalTextPosition(SwingConstants.BOTTOM);
                bt.setHorizontalTextPosition(SwingConstants.CENTER);
                bt.addActionListener(new MenuAcao());

                if ((i % 6) == 0) {
                    panelMesas.add(bt, "wrap");
                } else if ((i % 6) != 0) {
                    panelMesas.add(bt);
                }
        }//fim do for

        return panelMesas;
    }//fim butao automatico

    private class MenuAcao implements ActionListener {

        @Override
        public void actionPerformed(final ActionEvent e) {
            JPopupMenu pop = new JPopupMenu();

            JMenuItem menuPagamento = new JMenuItem("Efectuar Pagamento",new ImageIcon(ij.getImageIcon("/Imagens/dinheiro.png").getImage()));
            JMenuItem itemPedido = new JMenuItem("Adicionar Pedidos",new ImageIcon(ij.getImageIcon("/Imagens/venda.png").getImage()));

            menuPagamento.setFont(new Font("Serif", Font.PLAIN, 18));
            itemPedido.setFont(new Font("Serif", Font.PLAIN, 18));
            pop.add(itemPedido);
            pop.add(menuPagamento);
            pop.show((JButton) e.getSource(), 50, 50);

               menuPagamento.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent ev) {
                    listarMesa(obc.buscaMesas());
                }

                private void listarMesa(List<Mesas> mesa) {
                    boolean achou = false;
                    for (int i = 1; i < mesa.size() + 1; i++) {
                        Mesas mesas = mesa.get(i - 1);
                        if ((mesas.getLugares() == mesas.getTamanho()) && mesas.getNomeMesa().equals(e.getActionCommand())) {
                            achou = true; break;
                        }
                    }

                    if (achou) {
                        JOptionPane.showMessageDialog(null, "Adicione pedidos a Mesa,para efetuar pagamentos", "Messagem", 2);
                    } else {
                        btk = e.getActionCommand();
                        MenuPrincipal.panelComponentes.removeAll();
                        MenuPrincipal.panelComponentes.add(new TelaPagamentos());
                        MenuPrincipal.panelComponentes.validate();
                    }
                }
            });

            itemPedido.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ev) {
                    listarMesa(obc.buscaMesas(), false);
                }

                private void listarMesa(List<Mesas> mesa, boolean achou) {
                    for (Mesas mesas : mesa) {
                        if ((mesas.getLugares() == 0) && mesas.getNomeMesa().equals(e.getActionCommand())) {
                            achou = true;
                            break;
                        }
                    }

                    if (achou) {
                        JOptionPane.showMessageDialog(null, "Mesa Cheia!!!", "Messagem", 2);
                    } else {
                        MenuPrincipal.panelComponentes.removeAll();
                        MenuPrincipal.panelComponentes.add(new PainelVenda());
                        MenuPrincipal.panelComponentes.validate();
                        PainelVenda.jtMesa.setText(e.getActionCommand());
                    }
                }
            });
        }

    }//fim da classe interna acao

    private void buscarFoto() {
        JFileChooser jfc = new JFileChooser();
        ArrayList<String> cm = new ArrayList<>();
        jfc.setFileFilter(filter);
        int opcao = jfc.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            caminho = jfc.getSelectedFile().getPath();
            cm.add(caminho);
            am.armazenarBotoes(cm);
            mostraImagem(am.recuperarCaminho());
        }
    }

    private void mostraImagem(ArrayList<String> recuperarImagem) {
        for (int i = 0; i < recuperarImagem.size(); i++) {
            String caminho = recuperarImagem.get(i);
            ImageIcon imagem = new ImageIcon(caminho);
            Image img = imagem.getImage();
            Image newimg = img.getScaledInstance(450, 373, Image.SCALE_SMOOTH);
            ImageIcon imagem2 = new ImageIcon(newimg);
            lbImagem.setIcon(imagem2);
        }
    }
}
