/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ImagemJar;
import Controle.CRUD;
import Modelo.Clientes;
import Modelo.Funcionarios;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigues
 */
public class PainelClientes extends javax.swing.JPanel {

    CRUD obc = new CRUD();
    String[]linha={"Codigo","Nome","Apelido","Morada","Local de Trabalho","Contacto","Email","Estado"};
    DefaultTableModel modelo = new DefaultTableModel(linha,0);
    ImagemJar ij = new ImagemJar();

    /**
     * Creates new form PainelClientes
     */
    public PainelClientes() {
        initComponents();
        inicializaTabela();
        ButtonGroup g = new ButtonGroup();
        g.add(btAtivar);
        g.add(btDesativar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbitulo = new javax.swing.JLabel();
        panelComponentes = new javax.swing.JPanel();
        jtEmail = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbApelido = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        lbTrabalho = new javax.swing.JLabel();
        lbContacto = new javax.swing.JLabel();
        jtContacto = new javax.swing.JTextField();
        jtApelido = new javax.swing.JTextField();
        jtMorada = new javax.swing.JTextField();
        lbMorada = new javax.swing.JLabel();
        jtTrabalho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        panelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtPesquisar = new javax.swing.JTextField();
        btAtivar = new javax.swing.JRadioButton();
        btDesativar = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(51, 141, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbitulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbitulo.setText("Formulário de Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addComponent(lbitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 939, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComponentes.setBackground(new java.awt.Color(255, 255, 255));
        panelComponentes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        jtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtEmailKeyTyped(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNome.setText("Nomes : ");

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEmail.setText("Email:");

        lbApelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbApelido.setText("Apelido:");

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNomeKeyTyped(evt);
            }
        });

        lbTrabalho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTrabalho.setText("Local Trabalho:");

        lbContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbContacto.setText("Contacto: ");

        jtContacto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtContactoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtContactoKeyTyped(evt);
            }
        });

        jtApelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtApelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtApelidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtApelidoKeyTyped(evt);
            }
        });

        jtMorada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtMorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtMoradaActionPerformed(evt);
            }
        });
        jtMorada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtMoradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtMoradaKeyTyped(evt);
            }
        });

        lbMorada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMorada.setText("Morada:");

        jtTrabalho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtTrabalho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTrabalhoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtTrabalhoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        javax.swing.GroupLayout panelComponentesLayout = new javax.swing.GroupLayout(panelComponentes);
        panelComponentes.setLayout(panelComponentesLayout);
        panelComponentesLayout.setHorizontalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(lbApelido)
                        .addGap(2, 2, 2)
                        .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addComponent(lbNome)
                        .addGap(5, 5, 5)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(lbMorada)
                        .addGap(0, 0, 0)
                        .addComponent(jtMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbEmail)
                        .addGap(4, 4, 4)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(lbTrabalho)
                        .addGap(7, 7, 7)
                        .addComponent(jtTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)
                        .addGap(0, 0, 0)
                        .addComponent(lbContacto)
                        .addGap(4, 4, 4)
                        .addComponent(jtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelComponentesLayout.setVerticalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbApelido))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbNome))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lbMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtMorada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbEmail))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbTrabalho))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelBotoes.setBackground(new java.awt.Color(255, 255, 255));
        panelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.setBorderPainted(false);
        btGravar.setContentAreaFilled(false);
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        btRemover.setText("Remover");
        btRemover.setBorderPainted(false);
        btRemover.setContentAreaFilled(false);
        btRemover.setEnabled(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/update2.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setBorderPainted(false);
        btAtualizar.setContentAreaFilled(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Broom.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelTabela.setBackground(new java.awt.Color(255, 255, 255));
        panelTabela.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        tabelaClientes = new javax.swing.JTable(){
            public boolean isCellEditable(int a,int b){
                return false;
            }
        };
        tabelaClientes.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaClientes);

        lbErro.setBackground(new java.awt.Color(255, 255, 255));
        lbErro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 30, 26);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPesquisar.setForeground(new java.awt.Color(204, 204, 204));
        jtPesquisar.setText("Pesquisar clientes por nome,apelido ou codigo");
        jtPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisarActionPerformed(evt);
            }
        });
        jtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusLost(evt);
            }
        });
        jtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyReleased(evt);
            }
        });
        jPanel3.add(jtPesquisar);
        jtPesquisar.setBounds(30, 6, 440, 20);

        btAtivar.setBackground(new java.awt.Color(255, 255, 255));
        btAtivar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtivar.setText("Ativar Cliente");
        btAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtivarActionPerformed(evt);
            }
        });

        btDesativar.setBackground(new java.awt.Color(255, 255, 255));
        btDesativar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDesativar.setText("Desativar Cliente");
        btDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesativarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTabelaLayout = new javax.swing.GroupLayout(panelTabela);
        panelTabela.setLayout(panelTabelaLayout);
        panelTabelaLayout.setHorizontalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addGroup(panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTabelaLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTabelaLayout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(btAtivar)
                        .addGap(25, 25, 25)
                        .addComponent(btDesativar))
                    .addGroup(panelTabelaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTabelaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lbErro, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelTabelaLayout.setVerticalGroup(
            panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelTabelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAtivar)
                    .addComponent(btDesativar))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lbErro, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        gravar();
    }//GEN-LAST:event_btGravarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        removerNaTabela();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizarNaTabela();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        jtApelido.setText("");
        jtContacto.setText("");
        jtEmail.setText("");
        jtMorada.setText("");
        jtNome.setText("");
        jtTrabalho.setText("");

    }//GEN-LAST:event_btLimparActionPerformed

    private void jtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisarActionPerformed

    private void jtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusGained
        jtPesquisar.setText("");
        jtPesquisar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtPesquisarFocusGained

    private void jtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusLost
        jtPesquisar.setText("Pesquisar clientes por nome,apelido ou codigo");
        corPesquisar();
    }//GEN-LAST:event_jtPesquisarFocusLost

    private void jtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyReleased
        pesquisarClientes(jtPesquisar.getText(), obc.buscaClientess(), new ArrayList<Clientes>());
    }//GEN-LAST:event_jtPesquisarKeyReleased

    private void jtApelidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApelidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtNome.grabFocus();
        }
    }//GEN-LAST:event_jtApelidoKeyPressed

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtMorada.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtMoradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMoradaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtEmail.grabFocus();
        }
    }//GEN-LAST:event_jtMoradaKeyPressed

    private void jtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtTrabalho.grabFocus();
        }
    }//GEN-LAST:event_jtEmailKeyPressed

    private void jtTrabalhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTrabalhoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtContacto.grabFocus();
        }
    }//GEN-LAST:event_jtTrabalhoKeyPressed

    private void jtContactoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtContactoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            gravar();
        }
    }//GEN-LAST:event_jtContactoKeyPressed

    private void jtContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtContactoKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jtContactoKeyTyped

    private void btAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtivarActionPerformed
        int idx = tabelaClientes.getSelectedRow();
        if (idx != -1) {
            ativarCliente(obc.buscaClientess(), (int) tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione o Cliente que Desaja Ativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btAtivarActionPerformed

    private void btDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesativarActionPerformed
        int idx = tabelaClientes .getSelectedRow();
        if (idx != -1) {
            desativarCliente(obc.buscaClientess(), (int) tabelaClientes.getValueAt(tabelaClientes.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione o Cliente que Desaja Desativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btDesativarActionPerformed

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void jtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' | c > 'Z')&& (c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtNomeKeyTyped

    private void jtApelidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApelidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' | c > 'Z')&& (c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtApelidoKeyTyped

    private void jtMoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtMoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtMoradaActionPerformed

    private void jtTrabalhoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTrabalhoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' | c > 'Z')&&(c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtTrabalhoKeyTyped

    private void jtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEmailKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z')&&(c < '0' || c > '9')&& (c < '@'||c > '@')&& (c < '.'||c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtEmailKeyTyped

    private void jtMoradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtMoradaKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z')&&(c < 'A' || c > 'Z')&&(c < '0' || c > '9')&& (c < 'º'||c > 'º')&& (c < '.'||c > '.')&& (c < '-'||c > '-')&& (c < '/'||c > '/')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtMoradaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btAtivar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JRadioButton btDesativar;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtApelido;
    private javax.swing.JTextField jtContacto;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtMorada;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTextField jtTrabalho;
    private javax.swing.JLabel lbApelido;
    private javax.swing.JLabel lbContacto;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbErro;
    private javax.swing.JLabel lbMorada;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTrabalho;
    private javax.swing.JLabel lbitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelTabela;
    private javax.swing.JTable tabelaClientes;
    // End of variables declaration//GEN-END:variables

    private void inicializaTabela() {
        tabelaClientes.setModel(modelo);
        listarNaTabela(obc.buscaClientess());
        tabelaClientes.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                int codigo = tabelaClientes.getSelectedRow();
                jtNome.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 1)));
                jtApelido.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 2)));
                jtMorada.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 3)));
                jtTrabalho.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 4)));
                jtContacto.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 5)));
                jtEmail.setText(String.valueOf(tabelaClientes.getValueAt(codigo, 6)));
                lbErro.setText("");
            }

        });
    }

    public final void listarNaTabela(List<Clientes> cliente) {
        controlaLinhas();
        if (!cliente.isEmpty()) {
            for (int i = 0; i < cliente.size(); i++) {
                Clientes c = cliente.get(i);
                if (!c.getNomeCli().equalsIgnoreCase("cliente geral")) {
                    modelo.addRow(new Object[]{c.getCodCliente(), c.getNomeCli(), c.getApelidoCli(), c.getMoradaCli(), c.getTrabalhoCli(), c.getContactoCli(), c.getEmailCli(),c.getEstado()});
                }
            }
        }
    }
///=========================================

    public void atualizarNaTabela() {
        List<Clientes> ut = obc.buscaClientess();
        int codigo = tabelaClientes.getSelectedRow();
        if (codigo == -1) {
            lbErro.setText("Selecione o Cliente que deseja Atualizar!!!");
        } else {
            String nome = (String) tabelaClientes.getValueAt(codigo, 1);
            for (int i = 0; i < ut.size(); i++) {
                String nome2 = (String) tabelaClientes.getValueAt(i, 1);
                if (nome.equals(nome2)) {
                    ut.get(i).setNomeCli(jtNome.getText());
                    ut.get(i).setApelidoCli(jtApelido.getText());
                    ut.get(i).setMoradaCli(jtMorada.getText());
                    ut.get(i).setTrabalhoCli(jtTrabalho.getText());
                    ut.get(i).setContactoCli(jtContacto.getText());
                    ut.get(i).setEmailCli(jtEmail.getText());
                    obc.actualizar(ut.get(i));
                    JOptionPane.showMessageDialog(null, "Atualizado com Sucesso", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/update2.png").getImage()));
                    listarNaTabela(obc.buscaClientess());
                    break;
                }
            }
        }
    }

    //===========================================
    public void removerNaTabela() {
        List<Clientes> ut = obc.buscaClientess();
        int codigo = tabelaClientes.getSelectedRow();
        if (codigo == -1) {
            lbErro.setText("Selecione o Cliente que deseja remover!!!");
        } else {
            String nome = (String) tabelaClientes.getValueAt(codigo, 1);
            for (int i = 0; i < ut.size(); i++) {
                String nome2 = (String) tabelaClientes.getValueAt(i, 1);
                if (nome.equals(nome2)) {

                    int j = JOptionPane.showConfirmDialog(null, "Deseja realmente Remover Este Cliente", "Messagem", 2);
                    if (j == JOptionPane.OK_OPTION) {
                        obc.excluir(ut.get(i));
                        JOptionPane.showMessageDialog(null, "Removido com Sucesso!!!", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/Delete.png").getImage()));
                    }
                    listarNaTabela(obc.buscaClientess());
                    break;
                }
            }
        }

    }
    // Variables declaration - do not modify                     

    private void gravar() {
        boolean achou = false;
        if (jtNome.getText().equals("") && jtApelido.getText().equals("") && jtContacto.getText().equals("") && jtEmail.getText().equals("") && jtMorada.getText().equals("") && jtTrabalho.getText().equals("")) {
            lbErro.setText("Os Campos na podem estar vazios!!!");
        } else {
            List<Clientes> ut = obc.buscaClientess();
            for (int i = 0; i < ut.size(); i++) {
                if (ut.get(i).getNomeCli().equals(jtNome.getText())) {
                    achou = true;
                    break;
                }
            }

            if (achou) {

                lbErro.setText("Esse Cliente ja foi Salvo, Registe um novo Usuario!!!");
                //  JOptionPane.showMessageDialog(null,"Esse usuario ja foi Salvo, Registe um novo Usuario","Messagem",0);
            } else {
                Clientes cli = new Clientes(jtNome.getText(), jtApelido.getText(), jtMorada.getText(), jtContacto.getText(), jtEmail.getText(), jtTrabalho.getText(),"Ativo");
                obc.salvar(cli);
                lbErro.setText("");
                JOptionPane.showMessageDialog(null, "Salvado com Sucesso", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/salvar.png").getImage()));
                listarNaTabela(obc.buscaClientess());
            }
        }
    }//fim de gravar

    private void pesquisarClientes(String n, List<Clientes> cliente, ArrayList<Clientes> p) {
        for (int i = 0; i < cliente.size(); i++) {
            Clientes cli = cliente.get(i);
            if (cli.getNomeCli().toLowerCase().startsWith(n) || String.valueOf(cli.getCodCliente()).startsWith(n) || String.valueOf(cli.getApelidoCli()).toLowerCase().startsWith(n)) {
                p.add(cli);
            }
        }
        listarClientesPesquisados(p);
    }

    private void listarClientesPesquisados(ArrayList<Clientes> m) {
        controlaLinhas();
        for (int i = 0; i < m.size(); i++) {
            Clientes c = m.get(i);
            modelo.addRow(new Object[]{c.getCodCliente(), c.getNomeCli(), c.getApelidoCli(), c.getMoradaCli(), c.getTrabalhoCli(), c.getContactoCli(), c.getEmailCli()});
        }
    }

    private void controlaLinhas() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void corPesquisar() {
        jtPesquisar.setForeground(new Color(204, 204, 204));
    }

    private void ativarCliente(List<Clientes> cli, int id) {
        for (int i = 0; i < cli.size(); i++) {
            Clientes buscaFunc = cli.get(i);
            if (buscaFunc.getCodCliente() == id) {
                buscaFunc.setEstado("Ativo");
                obc.actualizar(buscaFunc);
                JOptionPane.showMessageDialog(null, "Usuario Ativado com Sucesso", "Messagem", 1);
                listarNaTabela(obc.buscaClientess());
                break;
            }
        }
    }

    private void desativarCliente(List<Clientes> cli, int id) {
        for (int i = 0; i < cli.size(); i++) {
            Clientes cliente = cli.get(i);
            if (cliente.getCodCliente() == id) {
                cliente.setEstado("Desativado");
                obc.actualizar(cliente);
                JOptionPane.showMessageDialog(null, "Usuario Ativado com Sucesso", "Messagem", 1);
                listarNaTabela(obc.buscaClientess());
                break;
            }
        }
    }

}
