package Visao;

import Controle.ImagemJar;
import Controle.CRUD;
import Modelo.Categoria;
import Modelo.Produtos;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigues
 */
public class PainelProdutos extends javax.swing.JPanel {

    CRUD obc = new CRUD();
    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de imagens", "jpg");
    private String caminho = "";
    String[] colunas = {"ID", "Descrição", "Categoria", "Preco", "Foto","Estado"};
    DefaultTableModel modelo = new DefaultTableModel(colunas, 0);
    /**
     * Creates new form PainelProdutos
     */
    ImagemJar ij = new ImagemJar();

    public PainelProdutos() {
        initComponents();
        inicializaTabela();
           ButtonGroup g = new ButtonGroup();
            g.add(btAtivar);
            g.add(btDesativar);
        tabelaProduto.getColumnModel().getColumn(1).setPreferredWidth(10);
        tabelaProduto.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabelaProduto.getColumnModel().getColumn(3).setPreferredWidth(50);
        tabelaProduto.getColumnModel().getColumn(1).setPreferredWidth(300);
        tabelaProduto.getColumnModel().getColumn(4).setPreferredWidth(400);
        btBuscarImagem.setVerticalTextPosition(SwingConstants.BOTTOM);
        btBuscarImagem.setHorizontalTextPosition(SwingConstants.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelComponentes = new javax.swing.JPanel();
        lbCategoria = new javax.swing.JLabel();
        lbFoto = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();
        jtFoto = new javax.swing.JTextField();
        jtCategoria = new javax.swing.JComboBox<>();
        lbNome = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        btBuscarImagem = new javax.swing.JButton();
        jtPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelImagem = new javax.swing.JPanel();
        lbImagem = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        btGravar = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btCategoria = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        panelProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        lbErro = new javax.swing.JLabel();
        lberro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtPesquisar = new javax.swing.JTextField();
        btAtivar = new javax.swing.JRadioButton();
        btDesativar = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(51, 141, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbTitulo.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Formulário de Produtos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbTitulo)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelComponentes.setBackground(new java.awt.Color(255, 255, 255));
        panelComponentes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N

        lbCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCategoria.setText("Categoria: ");

        lbFoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbFoto.setText("Foto:");

        lbPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPreco.setText("Preco:");

        jtFoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtFoto.setFocusable(false);
        jtFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtFotoActionPerformed(evt);
            }
        });
        jtFoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtFotoKeyPressed(evt);
            }
        });

        jtCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtCategoriaKeyPressed(evt);
            }
        });

        lbNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNome.setText("Nome: ");

        jtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });
        jtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtNomeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNomeKeyTyped(evt);
            }
        });

        btBuscarImagem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btBuscarImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AnexoImagem.png"))); // NOI18N
        btBuscarImagem.setToolTipText("Clique aqui para anexar uma Imagem");
        btBuscarImagem.setBorderPainted(false);
        btBuscarImagem.setContentAreaFilled(false);
        btBuscarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarImagemActionPerformed(evt);
            }
        });

        jtPreco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtPrecoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPrecoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*");

        javax.swing.GroupLayout panelComponentesLayout = new javax.swing.GroupLayout(panelComponentes);
        panelComponentes.setLayout(panelComponentesLayout);
        panelComponentesLayout.setHorizontalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(lbNome)
                .addGap(5, 5, 5)
                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbFoto)
                .addGap(7, 7, 7)
                .addComponent(jtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btBuscarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(lbCategoria)
                .addGap(3, 3, 3)
                .addComponent(jtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPreco)
                .addGap(10, 10, 10)
                .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(470, 470, 470)
                .addComponent(jLabel5))
        );
        panelComponentesLayout.setVerticalGroup(
            panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelComponentesLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbNome))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btBuscarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelComponentesLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelComponentesLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelComponentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImagem.setBackground(new java.awt.Color(255, 255, 255));
        panelImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbImagem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/semImagem.jpg"))); // NOI18N

        javax.swing.GroupLayout panelImagemLayout = new javax.swing.GroupLayout(panelImagem);
        panelImagem.setLayout(panelImagemLayout);
        panelImagemLayout.setHorizontalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        panelImagemLayout.setVerticalGroup(
            panelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        panelBotoes.setBackground(new java.awt.Color(255, 255, 255));
        panelBotoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btGravar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btGravar.setText("Gravar");
        btGravar.setBorderPainted(false);
        btGravar.setContentAreaFilled(false);
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/update2.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setBorderPainted(false);
        btAtualizar.setContentAreaFilled(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Vegetarian Food.png"))); // NOI18N
        btCategoria.setText("Categoria");
        btCategoria.setBorderPainted(false);
        btCategoria.setContentAreaFilled(false);
        btCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCategoriaActionPerformed(evt);
            }
        });

        btRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete.png"))); // NOI18N
        btRemover.setText("Remover");
        btRemover.setBorderPainted(false);
        btRemover.setContentAreaFilled(false);
        btRemover.setEnabled(false);
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Broom.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setBorderPainted(false);
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBotoesLayout.createSequentialGroup()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(btGravar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        panelProdutos.setBackground(new java.awt.Color(255, 255, 255));
        panelProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Produtos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 24), new java.awt.Color(0, 153, 255))); // NOI18N
        panelProdutos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaProduto = new javax.swing.JTable(){
            public boolean isCellEditable(int a,int b){
                return false;
            }
        };
        tabelaProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaProduto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaProduto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaProduto);

        panelProdutos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 104, 1118, 206));

        lbErro.setBackground(new java.awt.Color(255, 255, 255));
        lbErro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lbErro.setForeground(new java.awt.Color(255, 0, 0));
        panelProdutos.add(lbErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 520, 20));

        lberro.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lberro.setForeground(new java.awt.Color(255, 0, 0));
        panelProdutos.add(lberro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 314, 440, 20));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisa.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 30, 26);

        jtPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtPesquisar.setForeground(new java.awt.Color(204, 204, 204));
        jtPesquisar.setText("Pesquisar produtos por nome,categoria , codigo ou estado");
        jtPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtPesquisarActionPerformed(evt);
            }
        });
        jtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtPesquisarFocusLost(evt);
            }
        });
        jtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesquisarKeyReleased(evt);
            }
        });
        jPanel3.add(jtPesquisar);
        jtPesquisar.setBounds(30, 6, 440, 20);

        panelProdutos.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 480, 30));

        btAtivar.setBackground(new java.awt.Color(255, 255, 255));
        btAtivar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btAtivar.setText("Ativar Produto");
        btAtivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtivarActionPerformed(evt);
            }
        });
        panelProdutos.add(btAtivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 70, 140, -1));

        btDesativar.setBackground(new java.awt.Color(255, 255, 255));
        btDesativar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btDesativar.setText("Desativar Produto");
        btDesativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesativarActionPerformed(evt);
            }
        });
        panelProdutos.add(btDesativar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelComponentes, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelComponentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtFotoActionPerformed

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void btBuscarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarImagemActionPerformed
        buscarFoto();
    }

    private void buscarFoto() {
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(filter);
        int opcao = jfc.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION) {
            caminho = jfc.getSelectedFile().getPath();
            ImageIcon imagem = new ImageIcon(caminho);
            Image img = imagem.getImage();
            Image newimg = img.getScaledInstance(249, 160, Image.SCALE_SMOOTH);
            ImageIcon imagem2 = new ImageIcon(newimg);
            lbImagem.setIcon(imagem2);
            jtFoto.setText(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btBuscarImagemActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
            gravar(false);
    }//GEN-LAST:event_btGravarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        atualizarNaTabela(obc.buscaProduto(), tabelaProduto.getSelectedRow());
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCategoriaActionPerformed
        new CategoriaProduto().setVisible(true);
    }//GEN-LAST:event_btCategoriaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        jtNome.setText("");
        jtFoto.setText("");
        jtPreco.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void jtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtPesquisarActionPerformed

    private void jtPesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusGained
        jtPesquisar.setText("");
        jtPesquisar.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtPesquisarFocusGained

    private void jtPesquisarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtPesquisarFocusLost
        jtPesquisar.setText("Pesquisar produtos por nome,categoria ou codigo");
        corPesquisar();
    }//GEN-LAST:event_jtPesquisarFocusLost

    private void jtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesquisarKeyReleased
        pesquisarProdutos(jtPesquisar.getText(), obc.buscaProduto(), new ArrayList<Produtos>());
    }//GEN-LAST:event_jtPesquisarKeyReleased

    private void jtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtFoto.grabFocus();
        }
    }//GEN-LAST:event_jtNomeKeyPressed

    private void jtCategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCategoriaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtPreco.grabFocus();
        }
    }//GEN-LAST:event_jtCategoriaKeyPressed

    private void jtPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            gravar(false);
        }
    }//GEN-LAST:event_jtPrecoKeyPressed

    private void jtPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecoKeyTyped
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '.' || c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_jtPrecoKeyTyped

    private void jtFotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtFotoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jtCategoria.grabFocus();
        }
    }//GEN-LAST:event_jtFotoKeyPressed

    private void jtNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyReleased
     
    }//GEN-LAST:event_jtNomeKeyReleased

    private void jtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNomeKeyTyped
//        char c = evt.getKeyChar();
//        if ((c < 'a' || c > 'z') && (c < 'A' | c > 'Z')&&(c < '0' || c > '9')&& (c > ' ')) {
//            evt.consume();
//        }
    }//GEN-LAST:event_jtNomeKeyTyped

    private void btAtivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtivarActionPerformed
        int idx = tabelaProduto.getSelectedRow();
        if (idx != -1) {
            ativarProduto(obc.buscaProduto(), (int) tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione o Produto que Desaja Ativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btAtivarActionPerformed

    private void btDesativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesativarActionPerformed
        int idx = tabelaProduto .getSelectedRow();
        if (idx != -1) {
            desativarProduto(obc.buscaProduto(), (int) tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0));
        } else {
            JOptionPane.showMessageDialog(null, "Por favor!!!Selecione o Produto que Desaja Desativar.", "Messagem", 2);
        }
    }//GEN-LAST:event_btDesativarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        removerNaTabela();
    }//GEN-LAST:event_btRemoverActionPerformed
    private void desativarProduto(List<Produtos> pro, int id) {
        for (int i = 0; i < pro.size(); i++) {
            Produtos p = pro.get(i);
            if (p.getCodProd() == id) {
                p.setEstado("Desativado");
                obc.actualizar(p);
                JOptionPane.showMessageDialog(null, "Produto Desativado com Sucesso", "Messagem", 1);
                listarNaTabela(obc.buscaProduto());
                break;
            }
        }
    }
    private void ativarProduto(List<Produtos> pro, int id) {
        for (int i = 0; i < pro.size(); i++) {
            Produtos buscaFunc = pro.get(i);
            if (buscaFunc.getCodProd() == id) {
                buscaFunc.setEstado("Ativo");
                obc.actualizar(buscaFunc);
                JOptionPane.showMessageDialog(null, "Produto Ativado com Sucesso", "Messagem", 1);
                listarNaTabela(obc.buscaProduto());
                break;
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btAtivar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscarImagem;
    private javax.swing.JButton btCategoria;
    private javax.swing.JRadioButton btDesativar;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> jtCategoria;
    private javax.swing.JTextField jtFoto;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtPesquisar;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbErro;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel lbImagem;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lberro;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelComponentes;
    private javax.swing.JPanel panelImagem;
    private javax.swing.JPanel panelProdutos;
    private javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables

    private void inicializaTabela() {
         listarCategoria(obc.buscaTipoProdutos());
         tabelaProduto.setModel(modelo);
         listarNaTabela(obc.buscaProduto());
        tabelaProduto.addMouseListener(new MouseAdapter() {

            public void mousePressed(MouseEvent e) {
                int codigo = tabelaProduto.getSelectedRow();
                jtNome.setText(String.valueOf(tabelaProduto.getValueAt(codigo, 1)));
                jtCategoria.setSelectedItem((String) tabelaProduto.getValueAt(codigo, 2));
                jtPreco.setText(String.valueOf(tabelaProduto.getValueAt(codigo, 3)));
                jtFoto.setText(String.valueOf(tabelaProduto.getValueAt(codigo, 4)));
                lberro.setText("");
                caminho = String.valueOf(tabelaProduto.getValueAt(codigo, 4));
                if(!"".equals(caminho)){
                    ImageIcon imagem = new ImageIcon(caminho);
                    Image img = imagem.getImage();
                    Image newimg = img.getScaledInstance(249, 160, Image.SCALE_SMOOTH);
                    ImageIcon imagem2 = new ImageIcon(newimg);
                    lbImagem.setIcon(imagem2);    
                } else {
                    ImageIcon imagem = new ImageIcon(ij.getImageIcon("/Imagens/semImagem.jpg").getImage());
                    Image img = imagem.getImage();
                    Image newimg = img.getScaledInstance(249, 160, Image.SCALE_SMOOTH);
                    ImageIcon imagem2 = new ImageIcon(newimg);
                    lbImagem.setIcon(imagem2);  
                }
                

            }

        });
    }

    public void listarCategoria(List<Categoria> pc) {
        for (Categoria produtoCategoria : pc) {
            jtCategoria.addItem(produtoCategoria.getNomeCategoria());
        }
    }

    public void listarNaTabela(List<Produtos> prod) {
        controlaLinhas();
        if (!prod.isEmpty()) {
            for (int i = 0; i < prod.size(); i++) {
                Produtos p = prod.get(i);
                 modelo.addRow(new Object[]{p.getCodProd(), p.getNomeProd(), p.getCateg().getNomeCategoria(), p.getPreco(), p.getFoto(),p.getEstado()});
            }
        }
    }
///=====================================================================================================================================

    public void atualizarNaTabela(List<Produtos> prod, int codigo) {
        if (codigo == -1) {
            lberro.setText("Selecione o Usuario que deseja Atualizar!!!");
        } else {
            String nome = (String) tabelaProduto.getValueAt(codigo, 1);
            for (int i = 0; i < prod.size(); i++) {
                String nome2 = (String) tabelaProduto.getValueAt(i, 1);
                if (nome.equals(nome2)) {
                    prod.get(i).setNomeProd(jtNome.getText());
                    prod.get(i).setFoto(jtFoto.getText());
                    prod.get(i).setCateg(categoriaProduto(obc.buscaTipoProdutos(), jtCategoria.getSelectedItem().toString(), null));
                    prod.get(i).setPreco(Double.parseDouble(jtPreco.getText()));
                    obc.actualizar(prod.get(i));
                    JOptionPane.showMessageDialog(null, "Atualizado com Sucesso", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/update2.png").getImage()));
                    listarNaTabela(obc.buscaProduto());
                    break;
                }
            }
        }
    }

    //==============================================================================================================================================================
    public void removerNaTabela() {
     List<Produtos> ut = obc.buscaProduto();
        int codigo = tabelaProduto.getSelectedRow();
        if (codigo == -1) {
            lbErro.setText("Selecione o Produto que deseja remover!!!");
        } else {
            String nome = (String) tabelaProduto.getValueAt(codigo, 1);
            for (int i = 0; i < ut.size(); i++) {
                String nome2 = (String) tabelaProduto.getValueAt(i, 1);
                if (nome.equals(nome2)) {

                    int j = JOptionPane.showConfirmDialog(null, "Deseja realmente Remover Este Produto", "Messagem", 2);
                    if (j == JOptionPane.OK_OPTION) {
                        obc.excluir(ut.get(i));
                        JOptionPane.showMessageDialog(null, "Removido com Sucesso!!!", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/Delete.png").getImage()));
                    }
                    listarNaTabela(obc.buscaProduto());
                    break;
                }
            }
        }

    }//remover

    private void gravar(boolean achou) {
        if (jtNome.getText().equals("") && jtFoto.getText().equals("")) {
            lberro.setText("Os Campos na podem estar vazios!!!");
        } else {
            List<Produtos> ut = obc.buscaProduto();
            for (int i = 0; i < ut.size(); i++) {
                if (ut.get(i).getNomeProd().equals(jtNome.getText())) {
                    achou = true;
                    break;
                }
            }

            if (achou) {
                lberro.setText("Esse Produto ja foi Salvo, Registe um novo Produto!!!");
            } else {
                String way="";
                if(jtFoto.getText().equals("")){way="/Imagens/garlic.png";}else{way=jtFoto.getText();}
                Produtos pro = new Produtos(jtNome.getText(), Double.parseDouble(jtPreco.getText()),way, categoriaProduto(obc.buscaTipoProdutos(), jtCategoria.getSelectedItem().toString(), null),"Ativo");
                obc.salvar(pro);
                JOptionPane.showMessageDialog(null, "Salvado com Sucesso", "Messagem", 1, new ImageIcon(ij.getImageIcon("/Imagens/salvar.png").getImage()));
                lberro.setText("");
                listarNaTabela(obc.buscaProduto());
            }
        }
    }

    private void controlaLinhas() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private Categoria categoriaProduto(List<Categoria> buscaProdutos, String txt, Categoria p) {
        for (int i = 0; i < buscaProdutos.size(); i++) {
            Categoria get = buscaProdutos.get(i);
            if (get.getNomeCategoria().equals(txt)) {
                p = get;
            }
        }
        return p;
    }

    private void pesquisarProdutos(String n, List<Produtos> prod, ArrayList<Produtos> p) {
        for (int i = 0; i < prod.size(); i++) {
            Produtos pro = prod.get(i);
            if (pro.getNomeProd().toLowerCase().startsWith(n) || String.valueOf(pro.getCodProd()).startsWith(n) || String.valueOf(pro.getCateg().getNomeCategoria()).toLowerCase().startsWith(n)||pro.getEstado().toLowerCase().startsWith(n)) {
                p.add(pro);
            }
        }
        listarProdutosPesquisados(p);
    }

    private void listarProdutosPesquisados(ArrayList<Produtos> prod) {
        controlaLinhas();
        for (int i = 0; i < prod.size(); i++) {
            Produtos p = prod.get(i);
            modelo.addRow(new Object[]{p.getCodProd(), p.getNomeProd(), p.getCateg().getNomeCategoria(), p.getPreco(), p.getFoto(),p.getEstado()});
        }
    }

    private void corPesquisar() {
        jtPesquisar.setForeground(new Color(204, 204, 204));
    }
}
